### ISSUE TITLE
Please link to a demo for each project

### ISSUE THREAD

**Issue by tylercollier-devmtn** [DevMountain/GitHub-Standard#1]
It'd be great if all projects could have at least a visual of the final thing being built (website), and even better if it were a link to a working demo. It might be worth changing the template README to include such a section, like how on https://github.com/DevMountain/react-routing there is an h2 for **Live Example**.

An example of a project that would be helped by a link to a demo is https://github.com/DevMountain/node-sessions-afternoon.

Recently I wanted a demo of what was supposed to be built for https://apis.devmountain.com/routing/, so Brack built one for me at https://apis.devmountain.com/routing, but that's probably not the standard location for them.

**Comment by devlemire** [comment]
Live Example section added to the README layout.
